### ISSUE TITLE
 Join Layout node looses path when file is not available

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/HCS-Tools#32]
If the file is not available (e.g. server not mounted) it throws this error:

ERROR Load Layout Loading model settings failed

If I click to configure then the URL field is blank (THIS is the bug i guess). If I click configure in a List Files node, where the server is not available as well, then I still can see the chosen directory (field is not blank!).

Now, saving the workflow again - without doing anything or after editing something "downstream" - will probably loose the URL of the Join Layout node completely (a status that I have experienced recently), even when the file is available later. If you mount the server, still the URL stays blank. Only if you dont save, close, make file available (mount server) reopen the workflow then the URL is there.

Here is the error log: e.g the List Files nodes doesnt throw error, the Join Layout does while opening (in both cases the URL are not valid/available)

2012-11-19 10:25:44,627 ERROR ModalContext Load Layout : Loading model settings failed
2012-11-19 10:25:44,627 DEBUG ModalContext Load Layout : Loading model settings failed
java.lang.NullPointerException
at java.io.File.<init>(File.java:222)
at de.mpicbg.tds.core.ExcelLayout.openWorkbook(ExcelLayout.java:75)
at de.mpicbg.tds.core.ExcelLayout.<init>(ExcelLayout.java:53)
at de.mpicbg.tds.knime.hcstools.utils.node_loadlayout.LoadLayoutV2NodeModel.loadExcelSheet(LoadLayoutV2NodeModel.java:194)
at de.mpicbg.tds.knime.hcstools.utils.node_loadlayout.LoadLayoutV2NodeModel.validateSettings(LoadLayoutV2NodeModel.java:224)
at org.knime.core.node.Node.loadSettingsFrom(Node.java:553)
at org.knime.core.node.Node.load(Node.java:317)
at org.knime.core.node.NodePersistorVersion1xx.load(NodePersistorVersion1xx.java:688)
at org.knime.core.node.workflow.SingleNodeContainerPersistorVersion1xx.loadNodeContainer(SingleNodeContainerPersistorVersion1xx.java:332)
at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:6503)
at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:6411)
at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:6524)
at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:6411)
at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:6308)
at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:6253)
at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:6040)
at org.knime.workbench.editor2.LoadWorkflowRunnable.run(LoadWorkflowRunnable.java:159)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
2012-11-19 10:25:44,628 DEBUG ModalContext NodeContainer : Load Layout 4:59 has new state: EXECUTED
2012-11-19 10:25:44,630 DEBUG ModalContext NodeContainer : List Files 4:63 has new state: EXECUTED

**Comment by niederle** [comment]
(Martin)

**Comment by knime-mpicbg** [comment]
cannot be reproduced so far
